[package]
name = "assistant-platform"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
assistant-config.workspace = true
serde.workspace = true
thiserror.workspace = true
tracing.workspace = true
async-trait.workspace = true
tokio.workspace = true
cpal = "0.18.2"
hound = "3.5.1"
